name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Execute day1.py
      run: python day1.py

    - name: Zip Lambda function
      run: zip -j lambda_function.zip day1.py

    - name: Terraform Init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'

    - name: Upload file to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-west-2'
      run: python upload_to_s3.py input.txt advent-of-code-day

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 1200

    - name: Run Lambda function advent-of-code-day
      run: |
        aws lambda invoke --function-name advent-of-code-2023-day1 \
          --payload '{}' \
          --cli-binary-format raw-in-base64-out \
          response.json
        cat response.json

    - name: Upload output.txt to Athena table
      run: |
        # Create the Athena table if it doesn't exist
        aws athena start-query-execution \
          --query-string "CREATE EXTERNAL TABLE IF NOT EXISTS advent_output (line STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\n' STORED AS TEXTFILE LOCATION 's3://advent-of-code-day/'" \
          --result-configuration OutputLocation=s3://advent-of-code-day/athena_results/ \
          --query-execution-context Database=advent_database

        # Wait for the table creation query to complete
        sleep 10

        # Load data from output.txt into the Athena table
        aws athena start-query-execution \
          --query-string "INSERT INTO advent_output SELECT * FROM s3_table WHERE \"$path\" LIKE '%output.txt'" \
          --result-configuration OutputLocation=s3://advent-of-code-day/athena_results/ \
          --query-execution-context Database=advent_database

        echo "Data from output.txt has been loaded into the Athena table 'advent_output'"

    - name: Create Athena table and run query
      run: python lambda_athena.py

    - name: Display results and logs
      run: |
        cat query_results.md
        cat athena_debug.log

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Deploy to AWS
      run: |
        # Your deployment steps here
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-west-2  # or your preferred region




