name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-north-1'

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-north-1'

    - name: Zip Lambda function
      run: zip -j day1.zip day1.py  # Use -j to avoid directory structure in the zip

    - name: Upload file to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-north-1'  # or your desired region
      run: python upload_to_s3.py input.small.txt advent-of-code-day

   
    - name: Deploy to AWS Lambda
      run: |
        FUNCTION_NAME="advent-of-code-2023"
        if aws lambda get-function --function-name $FUNCTION_NAME 2>&1 | grep -q "Function not found"; then
          echo "Creating new Lambda function"
          aws lambda create-function \
            --function-name $FUNCTION_NAME \
            --runtime python3.8 \
            --role arn:aws:iam::418272766593:role/lambda-execution-role \
            --handler day1.lambda_handler \
            --zip-file fileb://day1.zip
        else
          echo "Updating existing Lambda function"
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://day1.zip
        fi